NAME		:= claptrap
CXX			:= g++
CXXFLAGS	:= -fsanitize=address -g -Wextra -Wall -Werror

SRCS		:= main.cpp ClapTrap.cpp
OBJS		:= $(SRCS:.cpp=.o)

all: $(NAME)

%.o: %.cpp
	@$(CXX) $(CXXFLAGS) -o $@ -c $< && printf "Compiling: $(notdir $<)\n"

$(NAME): $(OBJS)
	@$(CXX) $(CXXFLAGS) -o $(NAME) $(OBJS) && printf "Linking: $(NAME)\n"

clean:
	@rm -rf $(OBJS)

fclean: clean
	@rm -rf $(NAME)

re: fclean all

.PHONY: all clean fclean re